BASE_URL = "https://fakerestapi.azurewebsites.net/api/v1"
BOOKS_ENDPOINT = f"{BASE_URL}/Books"
COVER_PHOTOS_ENDPOINT = f"{BASE_URL}/CoverPhotos"
AUTHORS_ENDPOINT = f"{BASE_URL}/Authors"
USERS_ENDPOINT = f"{BASE_URL}/Users"
